[versions]
adsSdkPro = "6.8.2.0"
agp = "8.8.2"
dexkit = "2.0.4"
jjwt = "0.12.5"
kotlin = "2.0.10"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
okhttp = "4.10.0"
rxandroid = "3.0.2"
rxjava = "3.1.10"
yuki = "1.2.1"
xposed = "82"
ksp = "2.0.10-1.0.24"

[libraries]
ads-sdk-pro = { module = "com.pangle.cn:ads-sdk-pro", version.ref = "adsSdkPro" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-orgjson = { module = "io.jsonwebtoken:jjwt-orgjson", version.ref = "jjwt" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
yuki-api = { module = "com.highcapable.yukihookapi:api", version.ref = "yuki" }
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed" }
ksp-xposed = { module = "com.highcapable.yukihookapi:ksp-xposed", version.ref = "yuki" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
